### ISSUE TITLE
Add locks for pending transactions of a tokenName.

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/drep-id#1]
**When** a user inititates a transaction for a token `Token1` 
**and** if another user also begins minting `Token1`
**then** the  2nd user should not be allowed

**Comment by reeshavacharya** [comment]
## New flow
- `/api/register` : backend creates the transaction ans stores the transaction hash in database. Returns created transaction without signature in witnessSet. 
- user's wallet signs the transaction and submits the signed transaction to backend (/api/submit)
- `/api/submit` :  checks that the transaction hash is stored in the database (this validates that the transaction was created by backend). adds operator's signature in the witness and submits the transaction. this also returns txCbor and txHash.
- the received txCbor can be submitted by the user

## Pending Transaction Lock System
- when registering, check if a common DRep Name is present in database. If it is present, return "locked" error. if it is not present, store it in the database.
- when polling tx for submission, query assets in the tx and filter dRep token name. if tokenName exists in the database, remove it from the database after transaction conformation. 

> These are implemented in the backend and pushed to master branch
