### ISSUE TITLE
Add option to edit given name on DRep ID

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/drep-id#10]
Lets add option to edit the given name on DRep ID

**Comment by reeshavacharya** [comment]
- [x] Added `Edit Profile` section which opens a form to edit metadata (starting with name and image)
- [x] Display Drep's GivenName as profile name
- [x] Display DRep's minted token name as username with `@` and on the page title. 
- [x] Limit updating givenName to 80 characters (as per CIP)
 
<br/>  

![Image](https://github.com/user-attachments/assets/7e05b6f7-6707-4995-979f-661c17aef479)
![Image](https://github.com/user-attachments/assets/062cb177-617f-4e23-af09-48b161cdf161)
