### ISSUE TITLE
Update Drep profile page according to new design

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/drep-id#16]
https://www.figma.com/design/ADEOUkyBJhbYMDXJVCWkyV/DRep-Website-(New)
![Image](https://github.com/user-attachments/assets/acfe3f89-e3f3-42e7-93f1-2a7be28a1775)

**Comment by spannercode** [comment]
Lets focus on showing the social icons only instead of the full design for now.

The icons should be below the handle.
For known social networks, the icon and user handle is shown.
For unknown links, `web` icon is shown along with the associated name.

**Comment by JosephRana11** [comment]
Implementation of the Social Nav Icons is Complete and is merged into master branch , other updates are in hold.
