### ISSUE TITLE
User Flow Diagram for Viewer, Ada Holder, and dRep

### ISSUE THREAD

**Issue by kneerose** [cardanoapi/drep-id#24]
### Description 
This ticket is for creating a clear and visually engaging user flow diagram to represent the transitions and interactions between three types of users: Viewer, Ada Holder, and dRep. The diagram will help clarify the flow of actions and roles within the application, specifically in the context of the dRep profile.

### TODO
- Create a user flow diagram that includes:
         1. Viewer: Any users without a wallet connection
         2. Ada Holder: The user becomes an Ada Holder after connecting their wallet.
         3. dRep: Ada Holder becomes a dRep if the profile is verified as their own.

**Comment by kneerose** [comment]
User flow link in [Excalidraw](https://excalidraw.com/#json=td9MSqdDuKPS-HUS83T4j,t4XphfFOFBCxsJAWcncycg)

### 1. Viewer to dRep Flow

![Image](https://github.com/user-attachments/assets/ed7808da-3384-4b9a-b214-4e985936aeb2)

### 2. User flow
  **Viewer**
![Image](https://github.com/user-attachments/assets/be50a947-46af-41ab-bca1-63e508074474)

 **Ada holder**
![Image](https://github.com/user-attachments/assets/2e7cf9cb-33ae-45b5-9d5c-775f2e4b034c)

  **DRep**
![Image](https://github.com/user-attachments/assets/30da88a9-9cb6-42bf-ac20-1ca1be63ee0d)


### 3. Details ![Image](https://github.com/user-attachments/assets/3929c178-3614-44c8-9f09-9c34305e99eb)

**Comment by kneerose** [comment]
@spannercode dai, here is the user flow I have created. Please let me know if there is any missing part or something I have done incorrectly.

**Comment by spannercode** [comment]
@kneerose looks good, thanks 👍
