### ISSUE TITLE
Add additional APIs for DRep ID

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/drep-id#3]
Reference page: https://adastat.net/dreps/drep1y29wr22dde9qlfjywmwll56ft9ees7sx959xz4vhc8te43c99esu9
![Image](https://github.com/user-attachments/assets/067050ee-daba-49fc-aed9-d11ebfa70d1e)

**Comment by Sital999** [comment]
- Debug for image field in `drep_registration_metadata` and test it.

**Comment by Sital999** [comment]
- Fix drep list issue for multiple return of same drep
- Add filter by givenName in drepList
- Add endpoint for `drep votedetails`

**Comment by Sital999** [comment]
Add endpoints for
- #### DrepDelegationDetails
- [Preview DbSync Service Endpoint](https://preview-dbync.agents.cardanoapi.io/api/docs/#/default/get_api_drep__id__delegation)
##### JSON
```
{
  "utxoBalance": 427648,
  "currentDrepDelegateTime": "2024-08-12T03:45:09",
  "rewardBalance": 962929301,
  "rewardRestBalance": null,
  "drepView": "drep1z5cun68mz0jcemz0yyzqnmcxu4fl5q42dv5qvk",
  "prevDrepTxHash": "d91c7c464025f3331a361344f36add9813819dd2d68",
  "prevDrepEpochNo": 664,
  "prevDrepDelegateTime": "2024-08-19T03:18:29",
  "stakeAddress": "stake_tes2rfluhuwyk9saaw8hamx8044manhx9tqang8k5",
  "prevDrepName": "Name",
  "prevDrepImage": "",
  "hasScript": false
}
```
#### DrepDelegationDetails
- [Preview DbSync Service Endpoint](https://preview-dbync.agents.cardanoapi.io/api/docs/#/default/get_api_drep__id__registration)
##### JSON
```
 {
  "url": "https://xyz.com/drep-id/data/main/preview/test",
  "deposit": null,
  "drepName": "name",
  "time": "2024-12-12T08:11:03.000Z"
}
```
