### ISSUE TITLE
Explore adding and rendering image on DRep metadata

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/drep-id#4]
DRep metadata support image field. Lets explore how that works and how it can added and then rendered on the DRep profile.

Additional, possible to add additional metadata like cover image. Check person schema and add additional fields to see if those are recognized correctly or fails (?)

**Comment by reeshavacharya** [comment]
- [x] Person schema recognized correctly in DRep metadata

**Comment by reeshavacharya** [comment]
**Update**
- image field was set with image url can be displayed in drep profile.
