### ISSUE TITLE
Fix Wallet Network switch

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/drep-id#5]
When user connects wallet from testnet and then switches to mainnet, the platform is stuck in an intermediate state,
showing that the wallet is connected, but failing to do anything.

To Fix:
- when user changes wallet, auto disconnect .

![Image](https://github.com/user-attachments/assets/566b3b1a-33c5-4e49-a840-253223e5eccb)

**Comment by reeshavacharya** [comment]
## Fix
- The wallet's network ID is now saved in local storage.
- Each time an action is performed, the wallet's network ID is compared with the one stored in local storage.
- If the network changes, the wallet will be automatically disconnected:
    - During every action
    - Upon page reload
- This update has been deployed on preview.drep.id (please review).
