### ISSUE TITLE
Add status check for Drep.ID

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/drep-id#8]
Add status check for DRep.ID using uptime kuma at https://status.sireto.net

**Comment by reeshavacharya** [comment]
status check has been added: https://status.sireto.net/dashboard/17
dRepId health endpoint : https://drep.id/api/health
dbSync health endpoint: https://dbsyncapi.agents.cardanoapi.io/api/health
*Remaining* :  Deployment of indexer

**Comment by reeshavacharya** [comment]
**Update**
- Indexer has been deployed: https://drep.id/indexer/health
- health-check has been updated: https://drep.id/api/health
