### ISSUE TITLE
Image not loading on DRep ID

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/drep-id#9]
Not all image of DReps are loading correctly.

Here is an example DRep whose image is not loading on our platform.
https://adastat.net/dreps/drep1y2y9mhmsk8cglz6mj9wwjatxry9q264gkhwcg2pwxp4mpdcaj8w8h
https://drep.id/drep/drep13pwa7u937z8ckku3tn5h2esepgzk4294mkzzst3sdwctwt5eu5s

**Comment by reeshavacharya** [comment]
- [x] ImageObject parsed
- [x] Profile image is now visible : https://drep.id/drep/drep13pwa7u937z8ckku3tn5h2esepgzk4294mkzzst3sdwctwt5eu5s
